version: '3'

volumes:
  local_mongo_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: djongo_playground_local_django
    container_name: django
    depends_on:
      - mongo
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start

  mongo:
    build:
      context: .
      dockerfile: ./compose/local/mongo/Dockerfile
    image: djongo_playground_local_mongo
    container_name: mongo
    env_file:
      - ./.envs/.local/.mongo
    volumes:
      - local_mongo_data:/data/db
    ports:
      - "27017:27017"

#  docs:
#    image: djongo_playground_local_docs
#    container_name: docs
#    build:
#      context: .
#      dockerfile: ./compose/local/docs/Dockerfile
#    env_file:
#      - ./.envs/.local/.django
#    volumes:
#      - ./docs:/docs:z
#      - ./config:/app/config:z
#      - ./djongo_playground:/app/djongo_playground:z
#    ports:
#      - "7000:7000"
#    command: /start-docs
